version: 2
jobs:
  build1:
    working_directory: ~/Frontend/src/Components/AuthNav
    docker:
      - image: circleci/node:latest
    steps:
      - checkout:
           path: ~/Frontend
      - run: rm -r _snapshots_ 
  build2:
    working_directory: ~/Frontend/src/Components/LandingPage
    docker:
      - image: circleci/node:latest
    steps:
      - checkout:
           path: ~/Frontend
      - run: rm -r _snapshots_     
  build3:
    working_directory: ~/Frontend/src/Components/Tweet
    docker:
      - image: circleci/node:latest
    steps:
      - checkout:
           path: ~/Frontend
      - run: rm -r _snapshots_ 
  test:
    working_directory: ~/Frontend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install react-scripts
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build1
      - test:
          requires:
            - build1
            - build2
            - build3
          filters:
            branches:
              only: master
